# Generated by Django 5.0.9 on 2024-09-23 05:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_workout_date_alter_workout_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.workout_image_file_path),
        ),
    ]
