# Generated by Django 5.0.9 on 2024-09-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_workout_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
    ]
