# Generated by Django 5.0.9 on 2024-10-05 16:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(default=core.models.create_unique_invite_code, max_length=6, null=True),
        ),
    ]
