# Generated by Django 5.0.9 on 2024-10-11 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_workout_fires'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
