# Generated by Django 5.0.9 on 2024-10-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_workout_comments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
